---
- name: Get existing VMs
  block:
    - name: Include get vms task
      vars:
        app_tag: execution
        private_host_groups:
          - aap
          - execution_private
        public_host_groups:
          - execution_public
      tags:
        - execution
      ansible.builtin.include_tasks: vms/get.yml

- name: Set number of execution node VMs to create
  tags:
    - execution
  ansible.builtin.set_fact:
    infrastructure_execution_vms_to_create: "{{ infrastructure_execution_instances - (infrastructure_existing_vm.instances | default([]) | length) }}"

- name: Output number of VMs to create
  tags:
    - execution
  ansible.builtin.debug:
    msg: "Creating execution VMs: {{ infrastructure_execution_vms_to_create }}"

- name: Create VMs
  when: infrastructure_execution_vms_to_create | int > 0
  ignore_errors: true
  vars:
    subnet_index: "{{ lookup('ansible.utils.index_of', infrastructure_vpc_subnets, 'eq', 'execution', 'name') }}"
  block:
    - name: Include create vm task
      loop: "{{ query('sequence', 'start=1 end=' + (infrastructure_execution_vms_to_create | string)) }}"
      vars:
        instance_type: "{{ infrastructure_execution_shape }}"
        ami: "{{ infrastructure_execution_ami }}"
        vm_name_prefix: execution-
        private_host_groups:
          - aap
          - execution_private
        public_host_groups:
          - execution_public
        app_tag: execution
        subnet: "{{ infrastructure_subnet_ids[subnet_index | int] }}"
      tags:
        - execution
      ansible.builtin.include_tasks: vms/create.yml