---
- name: Set persistent tags
  tags:
    - always
  ansible.builtin.set_fact:
    persistent_tags:
      purpose: automation
      environment: ansible-automation-platform
      deployment: aap-infrastructure-{{ deployment_id }}

- name: Merge persistent tags with user defined tags
  tags:
    - always
  ansible.builtin.set_fact:
    _infrastructure_tags: "{{ infrastructure_tags | combine(persistent_tags) }}"
