---
- name: Upgrade all packages
  tags:
    - controller
    - hub
    - eda
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install required packages
  tags:
    - controller
    - hub
    - eda
  ansible.builtin.dnf:
    name:
      - python3-psycopg2
      - ansible-automation-platform-installer
    state: latest